name: Workflow 2

on:
  workflow_call:
    inputs:
      value: {type: string, required: true }
      conditional: {type: boolean, required: true }

jobs:
  _8c0322e9-a549-4c51-8662-29db9942edc6:
    name: Workflow 2 job (true)
    uses: ./.github/workflows/workflow3_${{ inputs.conditional }}.yaml
    with:
      value: ${{ inputs.value }}
